# Hardware config database for FireSim Simulation Manager
# See https://docs.fires.im/en/stable/Advanced-Usage/Manager/Manager-Configuration-Files.html for documentation of all of these params.

# Hardware configs represent a combination of an agfi, a deploytriplet override
# (if needed), and a custom runtime config (if needed)

# The AGFIs provided below are public and available to all users.
# Only AGFIs for the latest release of FireSim are guaranteed to be available.
# If you are using an older version of FireSim, you will need to generate your
# own images.

firesim_boom_singlecore_nic_l2_llc4mb_ddr3:
    agfi: agfi-03a8b870f4b855eb5
    deploy_triplet_override: null
    custom_runtime_config: null

firesim_boom_singlecore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-0450cb5f020467eb2
    deploy_triplet_override: null
    custom_runtime_config: null

firesim_rocket_quadcore_nic_l2_llc4mb_ddr3:
    agfi: agfi-0c98cee39819753e5
    deploy_triplet_override: null
    custom_runtime_config: null

firesim_rocket_quadcore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-0c7cd0bf5f0cb0264
    deploy_triplet_override: null
    custom_runtime_config: null

firesim_supernode_rocket_singlecore_nic_l2_lbp:
    agfi: agfi-0e9a315c33ca3e9e8
    deploy_triplet_override: null
    custom_runtime_config: null
