# Hardware config database for FireSim Simulation Manager
# See https://docs.fires.im/en/stable/Advanced-Usage/Manager/Manager-Configuration-Files.html for documentation of all of these params.

# Hardware configs represent a combination of an agfi, a deploytriplet override
# (if needed), and a custom runtime config (if needed)

# The AGFIs provided below are public and available to all users.
# Only AGFIs for the latest release of FireSim are guaranteed to be available.
# If you are using an older version of FireSim, you will need to generate your
# own images.

firesim_rocket_singlecore_sha3_no_nic_l2_llc4mb_ddr3_printf:
    agfi: agfi-0b811d62bd5294f45
    deploy_triplet_override: null
    custom_runtime_config: null

firesim_boom_singlecore_nic_l2_llc4mb_ddr3:
    agfi: agfi-054eaf0551f9f9b92
    deploy_triplet_override: null
    custom_runtime_config: null

firesim_boom_singlecore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-0cb2469984a15316e
    deploy_triplet_override: null
    custom_runtime_config: null

# DOCREF START: Example HWDB Entry
firesim_rocket_quadcore_nic_l2_llc4mb_ddr3:
    agfi: agfi-05c0f0acb0936780f
    deploy_triplet_override: null
    custom_runtime_config: null
# DOCREF END: Example HWDB Entry

firesim_rocket_quadcore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-00babb0dfc4d02654
    deploy_triplet_override: null
    custom_runtime_config: null

firesim_supernode_rocket_singlecore_nic_l2_lbp:
    agfi: agfi-0361e887d1934ee20
    deploy_triplet_override: null
    custom_runtime_config: null
