vitis_test:
    xclbin: https://firesim-ci-vitis-xclbins.s3.us-west-2.amazonaws.com/firesim_rocket_singlecore_no_nic_0b692d.xclbin
    deploy_triplet_override: FireSim-FireSimRocketConfig-BaseVitisConfig
    custom_runtime_config: null
