run_farm:
    base_recipe: run-farm-recipes/externally_provisioned.yaml
    recipe_arg_overrides:
        default_platform: VitisInstanceDeployManager
        default_simulation_dir: /scratch/buildbot
        run_farm_hosts_to_use:
            - localhost: four_fpgas_spec
        run_farm_host_specs:
            - four_fpgas_spec:
                num_fpgas: 4
                num_metasims: 0
                use_for_switch_only: false

metasimulation:
  metasimulation_enabled: false
  metasimulation_host_simulator: verilator
  metasimulation_only_plusargs: "+fesvr-step-size=128 +max-cycles=100000000"
  metasimulation_only_vcs_plusargs: "+vcs+initreg+0 +vcs+initmem+0"

target_config:
    topology: no_net_config
    no_net_num_nodes: 1
    link_latency: 6405
    switching_latency: 10
    net_bandwidth: 200
    profile_interval: -1
    default_hw_config: vitis_test
    plusarg_passthrough: ""

tracing:
    enable: no
    output_format: 0
    selector: 1
    start: 0
    end: -1

autocounter:
    read_rate: 0

workload:
    workload_name: outputs.json
    terminate_on_completion: no
    suffix_tag: null

host_debug:
    zero_out_dram: no
    disable_synth_asserts: no

synth_print:
    start: 0
    end: -1
    cycle_prefix: yes
